import type { DB } from './db'
import { autoGenerateDigest, todayLocalISODate } from './digest'

const FOUR_HOURS_MS = 4 * 60 * 60 * 1000

/**
 * Fires every 4 hours at local clock boundaries (00:00, 04:00, 08:00, 12:00, 16:00, 20:00).
 * Regenerates today's digest if there's been new activity since the last run.
 * Silently no-ops on provider errors (user can always trigger manually).
 */
export class DigestScheduler {
  private timeout: NodeJS.Timeout | null = null
  private running = false
  private lastRun: { at: string; status: string } | null = null
  private nextRunAt: Date | null = null

  constructor(private db: DB) {}

  start(): void {
    if (this.timeout) return
    // If the app just opened and today's digest is older than 4h, try once now.
    this.maybeRunNow()
    this.scheduleNext()
  }

  stop(): void {
    if (this.timeout) clearTimeout(this.timeout)
    this.timeout = null
  }

  getStatus(): { nextRunAt: string | null; lastRun: { at: string; status: string } | null } {
    return {
      nextRunAt: this.nextRunAt ? this.nextRunAt.toISOString() : null,
      lastRun: this.lastRun
    }
  }

  private scheduleNext(): void {
    const next = nextFourHourBoundary(new Date())
    this.nextRunAt = next
    const delay = Math.max(5_000, next.getTime() - Date.now())
    this.timeout = setTimeout(() => {
      void this.run().finally(() => this.scheduleNext())
    }, delay)
  }

  private maybeRunNow(): void {
    // If digest for today doesn't exist OR is older than 4h, kick off a run.
    const today = todayLocalISODate()
    const row = this.db
      .prepare('SELECT generated_at FROM digests WHERE date = ?')
      .get(today) as { generated_at?: string } | undefined
    const lastMs = row?.generated_at ? Date.parse(row.generated_at) : 0
    if (!lastMs || Date.now() - lastMs >= FOUR_HOURS_MS) {
      // Short delay so we don't block startup.
      setTimeout(() => void this.run(), 15_000)
    }
  }

  private async run(): Promise<void> {
    if (this.running) return
    this.running = true
    try {
      const date = todayLocalISODate()
      const result = await autoGenerateDigest(this.db, date)
      this.lastRun = { at: new Date().toISOString(), status: result.status }
      console.log(`[digest-scheduler] ${date} → ${result.status}`)
    } catch (err) {
      this.lastRun = {
        at: new Date().toISOString(),
        status: 'error: ' + (err instanceof Error ? err.message : String(err))
      }
      console.error('[digest-scheduler] run failed:', err)
    } finally {
      this.running = false
    }
  }
}

function nextFourHourBoundary(from: Date): Date {
  // 00, 04, 08, 12, 16, 20 local.
  const d = new Date(from)
  d.setMinutes(0, 0, 0)
  const hour = d.getHours()
  const nextHour = Math.floor(hour / 4) * 4 + 4
  d.setHours(nextHour)
  if (d.getTime() <= from.getTime()) d.setHours(d.getHours() + 4)
  return d
}
