import fs from 'node:fs'
import fsp from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import { spawn } from 'node:child_process'
import Anthropic from '@anthropic-ai/sdk'
import type { DB } from './db'
import type {
  ContentBlock,
  DigestDoc,
  DigestInfo,
  DigestRef,
  Settings,
  ToolName
} from '@shared/types'
import { formatHM } from '@shared/datetime'
import { loadSettings } from './settings'
import { readSessionDoc } from './sessionRead'
import {
  hasStructuredDigest,
  readDigestDoc,
  writeStructuredDigest,
  type ParsedItem,
  type ParsedSection
} from './digestStore'

const MAX_PROMPT_CHARS = 180_000
const PER_EVENT_TEXT_MAX = 1200

export interface DigestResult {
  status: 'generated' | 'skipped-no-activity' | 'skipped-no-new-activity'
  info: DigestInfo | null
}

export async function generateDigest(db: DB, date: string): Promise<DigestInfo> {
  const res = await generateDigestInternal(db, date, { forceIfNoActivity: true })
  if (!res.info) throw new Error(`No sessions found for ${date}`)
  return res.info
}

export async function autoGenerateDigest(db: DB, date: string): Promise<DigestResult> {
  return generateDigestInternal(db, date, { forceIfNoActivity: false, skipIfNoNewActivity: true })
}

interface GenerateOpts {
  forceIfNoActivity: boolean
  skipIfNoNewActivity?: boolean
}

async function generateDigestInternal(
  db: DB,
  date: string,
  opts: GenerateOpts
): Promise<DigestResult> {
  const settings = loadSettings()
  const window = localDayWindow(date)
  const sessions = findSessionsInWindow(db, window.startIso, window.endIso)
  if (sessions.length === 0) {
    if (opts.forceIfNoActivity) return { status: 'skipped-no-activity', info: null }
    return { status: 'skipped-no-activity', info: null }
  }

  if (opts.skipIfNoNewActivity) {
    const prev = db
      .prepare('SELECT generated_at FROM digests WHERE date = ?')
      .get(date) as { generated_at?: string } | undefined
    if (prev?.generated_at) {
      const mostRecent = sessions.reduce<string | null>((acc, s) => {
        const t = s.endedAt ?? s.startedAt
        if (!t) return acc
        if (!acc || t > acc) return t
        return acc
      }, null)
      if (mostRecent && mostRecent <= prev.generated_at) {
        return { status: 'skipped-no-new-activity', info: null }
      }
    }
  }

  const digestsDir = settings.digestsDir
  await fsp.mkdir(digestsDir, { recursive: true })
  const outPath = path.join(digestsDir, `${date}.md`)

  // Build a chronological cross-tool timeline carrying stable refIds.
  const refs = await buildReferences(db, sessions)
  const prompt = buildPrompt(date, refs, sessions)
  const text = await callProvider(settings, SYSTEM_PROMPT, prompt, { jsonMode: true })

  const parsed = parseModelResponse(text)
  const generatedAt = new Date().toISOString()

  // Upsert the parent digests row first so FK constraints from structured tables hold.
  // INSERT OR REPLACE cascades-deletes children, which writeStructuredDigest then refills.
  db.prepare(
    'INSERT OR REPLACE INTO digests (date, path, generated_at) VALUES (?, ?, ?)'
  ).run(date, outPath, generatedAt)

  let body: string
  if (parsed) {
    const sections = normalizeSections(parsed, refs)
    writeStructuredDigest(db, date, sections, refs)
    body = renderStructuredMarkdown(date, sections, sessions)
  } else {
    body = renderMarkdownFallback(date, text, sessions)
  }

  await fsp.writeFile(outPath, body, 'utf8')

  // The source has changed — any cached translations are now stale.
  db.prepare('DELETE FROM digest_translations WHERE date = ?').run(date)

  return { status: 'generated', info: { date, path: outPath, generatedAt } }
}

// --- windowing & selection ---

interface DaySession {
  id: string
  tool: ToolName
  projectName: string
  messageCount: number
  startedAt: string | null
  endedAt: string | null
}

function localDayWindow(date: string): { startIso: string; endIso: string } {
  const [y, m, d] = date.split('-').map(Number)
  if (!y || !m || !d) throw new Error(`Invalid date: ${date}`)
  const start = new Date(y, m - 1, d, 0, 0, 0, 0)
  const end = new Date(y, m - 1, d, 23, 59, 59, 999)
  return { startIso: start.toISOString(), endIso: end.toISOString() }
}

function findSessionsInWindow(db: DB, startIso: string, endIso: string): DaySession[] {
  return db
    .prepare<[string, string, string, string], DaySession>(
      `SELECT id,
              tool,
              project_name as projectName,
              message_count as messageCount,
              started_at as startedAt,
              ended_at as endedAt
         FROM sessions
        WHERE (started_at BETWEEN ? AND ?)
           OR (ended_at   BETWEEN ? AND ?)
        ORDER BY started_at ASC`
    )
    .all(startIso, endIso, startIso, endIso)
}

// --- references (timeline with stable refIds) ---

export async function buildReferences(db: DB, sessions: DaySession[]): Promise<DigestRef[]> {
  const out: DigestRef[] = []
  for (const s of sessions) {
    const doc = await readSessionDoc(db, s.id)
    for (const ev of doc.events) {
      if (ev.kind !== 'user' && ev.kind !== 'assistant') continue
      if (!ev.timestamp) continue
      const text = extractText(ev.content).trim()
      if (!text) continue
      const snippet = text.length > PER_EVENT_TEXT_MAX ? text.slice(0, PER_EVENT_TEXT_MAX) + '…' : text
      out.push({
        refId: '', // assigned after sort
        sessionId: s.id,
        eventUuid: ev.uuid,
        timestamp: ev.timestamp,
        tool: doc.meta.tool,
        projectName: doc.meta.projectName,
        role: ev.kind === 'user' ? 'USER' : 'ASSISTANT',
        snippet
      })
    }
  }
  out.sort((a, b) => a.timestamp.localeCompare(b.timestamp))
  out.forEach((r, i) => (r.refId = `R${i + 1}`))
  return out
}

// --- prompt building ---

function buildPrompt(date: string, refs: DigestRef[], sessions: DaySession[]): string {
  const summary = sessionsSummary(sessions)
  const schema = `Respond with ONE JSON object only — no prose before or after, no code fences. Schema:

{
  "sections": [
    {
      "id": "highlights",
      "heading": "Highlights",
      "kind": "bullets",
      "items": [{ "text": "<one bullet, plain markdown, NO leading dash>", "refs": ["R3","R7"] }],
      "refs": []
    },
    {
      "id": "projects",
      "heading": "Projects worked on",
      "kind": "paragraph",
      "body": "<one paragraph per project>",
      "items": [],
      "refs": ["R1","R5"]
    },
    {
      "id": "open-loops",
      "heading": "Open loops",
      "kind": "bullets",
      "items": [{ "text": "...", "refs": ["R..."] }],
      "refs": []
    },
    {
      "id": "reflection",
      "heading": "Reflection",
      "kind": "mixed",
      "body": "<final reflective question on its own line>",
      "items": [{ "text": "<one observation>", "refs": ["R..."] }],
      "refs": []
    }
  ]
}

Rules:
- Each item.refs / section.refs MUST be IDs that appear in the REFERENCES block below (e.g. "R3").
- Cite 1–4 references per item, more for paragraph/section-level refs as fits.
- Highlights: 3–5 bullets. Open loops: only what's actually unfinished. Reflection: 2–4 observations + one question in "body".
- "text"/"body" are plain markdown. Do not include "- " or "* " bullet markers — they are added by the renderer.
- Be concise, concrete, honest. Avoid filler.`

  const header = `Date: ${date}\n\n${summary}\n\n---\n\n${schema}\n\n---\n\n## REFERENCES\n\n`

  const lines: string[] = []
  for (const r of refs) {
    const hhmm = formatHM(r.timestamp)
    lines.push(`[${r.refId}] [${hhmm}] [${r.tool}] ${r.projectName} :: ${r.role}:\n${r.snippet}\n`)
  }

  let body = lines.join('\n')
  const budget = MAX_PROMPT_CHARS - header.length - 400
  if (body.length > budget) {
    body = body.slice(0, budget) + '\n\n[references truncated — exceeded size budget]'
  }
  return header + body
}

function sessionsSummary(sessions: DaySession[]): string {
  const byTool = new Map<ToolName, number>()
  const byProject = new Map<string, number>()
  for (const s of sessions) {
    byTool.set(s.tool, (byTool.get(s.tool) ?? 0) + 1)
    byProject.set(s.projectName, (byProject.get(s.projectName) ?? 0) + s.messageCount)
  }
  const tools = [...byTool.entries()].map(([t, n]) => `${t}: ${n}`).join(', ')
  const projects = [...byProject.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 10)
    .map(([p, n]) => `${p} (${n} msgs)`)
    .join(', ')
  return `Sessions: ${sessions.length} [${tools}]. Top projects: ${projects}.`
}

// --- response parsing ---

interface ModelSection {
  id: string
  heading: string
  kind: string
  body?: string
  items?: { text: string; refs?: string[] }[]
  refs?: string[]
}
interface ModelResponse {
  sections: ModelSection[]
}

export function parseModelResponse(text: string): ModelResponse | null {
  if (!text) return null
  // Strip code fences if present.
  let s = text.trim()
  s = s.replace(/^```(?:json)?\s*/i, '').replace(/```\s*$/i, '').trim()
  // Fall back to the first balanced object.
  if (!s.startsWith('{')) {
    const start = s.indexOf('{')
    const end = s.lastIndexOf('}')
    if (start === -1 || end === -1 || end <= start) return null
    s = s.slice(start, end + 1)
  }
  try {
    const obj = JSON.parse(s) as unknown
    if (!obj || typeof obj !== 'object') return null
    const sections = (obj as { sections?: unknown }).sections
    if (!Array.isArray(sections)) return null
    const valid = sections.every(
      (sec) =>
        sec &&
        typeof sec === 'object' &&
        typeof (sec as ModelSection).id === 'string' &&
        typeof (sec as ModelSection).heading === 'string' &&
        typeof (sec as ModelSection).kind === 'string'
    )
    if (!valid) return null
    return obj as ModelResponse
  } catch {
    return null
  }
}

function normalizeSections(resp: ModelResponse, refs: DigestRef[]): ParsedSection[] {
  const validIds = new Set(refs.map((r) => r.refId))
  const out: ParsedSection[] = []
  resp.sections.forEach((sec, idx) => {
    const kind = (sec.kind === 'bullets' || sec.kind === 'paragraph' || sec.kind === 'mixed')
      ? sec.kind
      : 'paragraph'
    const sectionId = slugify(sec.id || sec.heading) || `section-${idx + 1}`
    const sectionRefIds = (sec.refs ?? []).filter((r) => validIds.has(r))
    const items: ParsedItem[] = []
    const rawItems = Array.isArray(sec.items) ? sec.items : []
    rawItems.forEach((it, i) => {
      const t = typeof it.text === 'string' ? it.text.trim() : ''
      if (!t) return
      const itemRefs = Array.isArray(it.refs) ? it.refs.filter((r) => validIds.has(r)) : []
      items.push({ itemId: `i${i + 1}`, textMd: t, refIds: itemRefs })
    })

    let bodyMd = ''
    if (kind === 'paragraph') bodyMd = (sec.body ?? '').trim()
    else if (kind === 'mixed') bodyMd = (sec.body ?? '').trim()
    // For 'bullets' kind, bodyMd is constructed from items at render time too,
    // but we cache a markdown version for the .md file & raw view.
    const sectionBodyMd = renderSectionBodyMd(kind, bodyMd, items)

    out.push({
      sectionId,
      ord: idx,
      heading: sec.heading.trim() || prettyHeading(sectionId),
      kind,
      bodyMd: sectionBodyMd,
      items,
      refIds: sectionRefIds
    })
  })
  return out
}

function slugify(s: string): string {
  return s
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

function prettyHeading(slug: string): string {
  return slug
    .split('-')
    .filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join(' ')
}

export function renderSectionBodyMd(
  kind: 'bullets' | 'paragraph' | 'mixed',
  body: string,
  items: { textMd: string }[]
): string {
  if (kind === 'paragraph') return body
  const bullets = items.map((it) => `- ${it.textMd}`).join('\n')
  if (kind === 'bullets') return bullets
  // mixed: items as bullets, then body as a trailing line (e.g. reflection question)
  if (!bullets) return body
  if (!body) return bullets
  return `${bullets}\n\n${body}`
}

// --- markdown output ---

export function renderStructuredMarkdown(
  date: string,
  sections: ParsedSection[],
  sessions: DaySession[]
): string {
  const parts: string[] = [`# Work Diary — ${date}`, '']
  for (const sec of sections) {
    parts.push(`## ${sec.heading}`)
    parts.push('')
    parts.push(sec.bodyMd.trim())
    parts.push('')
  }
  parts.push('---')
  parts.push('')
  parts.push('## Sessions covered')
  parts.push(renderSessionsCovered(sessions))
  parts.push('')
  return parts.join('\n')
}

export function renderDocMarkdown(doc: DigestDoc, sessions: DaySession[]): string {
  const fakeParsed: ParsedSection[] = doc.sections.map((s, i) => ({
    sectionId: s.sectionId,
    ord: i,
    heading: s.heading,
    kind: s.kind,
    bodyMd: s.bodyMd,
    items: s.items.map((it) => ({ itemId: it.itemId, textMd: it.textMd, refIds: [] })),
    refIds: []
  }))
  return renderStructuredMarkdown(doc.info.date, fakeParsed, sessions)
}

function renderSessionsCovered(sessions: DaySession[]): string {
  const perTool = new Map<ToolName, DaySession[]>()
  for (const s of sessions) {
    const arr = perTool.get(s.tool) ?? []
    arr.push(s)
    perTool.set(s.tool, arr)
  }
  return [...perTool.entries()]
    .map(([tool, list]) => {
      const rows = list
        .map(
          (s) =>
            `  - \`${s.projectName}\` · ${s.id.replace(/^codex:/, '').slice(0, 8)} · ${s.messageCount} msgs`
        )
        .join('\n')
      return `- **${tool}** — ${list.length} sessions\n${rows}`
    })
    .join('\n')
}

function renderMarkdownFallback(date: string, body: string, sessions: DaySession[]): string {
  return `# Work Diary — ${date}\n\n${body.trim()}\n\n---\n\n## Sessions covered\n${renderSessionsCovered(sessions)}\n`
}

// --- providers ---

export interface CallProviderOpts {
  jsonMode?: boolean
  /** Per-call override of the provider and/or model selected from settings. */
  overrides?: {
    provider?: Settings['digestProvider']
    model?: string
  }
}

export async function callProvider(
  settings: Settings,
  system: string,
  userPrompt: string,
  opts: CallProviderOpts = {}
): Promise<string> {
  const provider = opts.overrides?.provider ?? settings.digestProvider
  const modelOverride = opts.overrides?.model
  switch (provider) {
    case 'anthropic-api':
      return callAnthropicApi(settings, system, userPrompt, modelOverride)
    case 'openai-compatible':
      return callOpenAICompatible(settings, system, userPrompt, opts, modelOverride)
    case 'claude-cli':
    default:
      return callClaudeCli(settings, system, userPrompt, modelOverride)
  }
}

async function callClaudeCli(
  settings: Settings,
  system: string,
  userPrompt: string,
  modelOverride?: string
): Promise<string> {
  const bin = resolveClaudeCli(settings.claudeCliPath)
  const args = ['-p', '--bare', '--append-system-prompt', system]
  const model = modelOverride || settings.claudeCliModel
  if (model) args.push('--model', model)

  return new Promise<string>((resolve, reject) => {
    const proc = spawn(bin, args, {
      stdio: ['pipe', 'pipe', 'pipe'],
      env: { ...process.env }
    })
    let stdout = ''
    let stderr = ''
    proc.stdout.on('data', (d: Buffer) => {
      stdout += d.toString('utf8')
    })
    proc.stderr.on('data', (d: Buffer) => {
      stderr += d.toString('utf8')
    })
    proc.on('error', reject)
    proc.on('close', (code) => {
      if (code === 0) resolve(stdout)
      else reject(new Error(`claude CLI exited ${code}: ${stderr || stdout || '(no output)'}`))
    })
    proc.stdin.write(userPrompt)
    proc.stdin.end()
  })
}

function resolveClaudeCli(override?: string): string {
  const candidates = [
    override,
    process.env.CLAUDE_CLI_PATH,
    path.join(os.homedir(), '.local/bin/claude'),
    '/opt/homebrew/bin/claude',
    '/usr/local/bin/claude',
    '/usr/bin/claude'
  ].filter((c): c is string => Boolean(c))
  for (const c of candidates) {
    if (fs.existsSync(c)) return c
  }
  throw new Error(
    "`claude` CLI not found. Install Claude Code (https://claude.com/code) or set its path in Settings."
  )
}

async function callAnthropicApi(
  settings: Settings,
  system: string,
  userPrompt: string,
  modelOverride?: string
): Promise<string> {
  if (!settings.anthropicApiKey)
    throw new Error('Anthropic API key not set — configure it in Settings.')
  const client = new Anthropic({ apiKey: settings.anthropicApiKey })
  const msg = await client.messages.create({
    model: modelOverride || settings.anthropicModel || 'claude-opus-4-7',
    max_tokens: 16000,
    system,
    messages: [{ role: 'user', content: userPrompt }]
  })
  return msg.content
    .filter((b): b is Anthropic.TextBlock => b.type === 'text')
    .map((b) => b.text)
    .join('\n\n')
}

const TRANSIENT_STATUSES = new Set([429, 502, 503, 504])
const MAX_ATTEMPTS = 3

async function callOpenAICompatible(
  settings: Settings,
  system: string,
  userPrompt: string,
  opts: CallProviderOpts,
  modelOverride?: string
): Promise<string> {
  const base = (settings.openaiBaseUrl || '').replace(/\/$/, '')
  if (!base) throw new Error('OpenAI-compatible base URL not set — configure it in Settings.')
  const model = modelOverride || settings.openaiModel || 'gpt-4o-mini'
  const headers: Record<string, string> = { 'Content-Type': 'application/json' }
  if (settings.openaiApiKey) headers.Authorization = `Bearer ${settings.openaiApiKey}`

  const messages = [
    { role: 'system', content: system },
    { role: 'user', content: userPrompt }
  ]
  const maxOut = 16000
  const url = `${base}/chat/completions`
  const baseBody: Record<string, unknown> = { model, messages, max_completion_tokens: maxOut }
  if (opts.jsonMode) baseBody.response_format = { type: 'json_object' }

  let res: Response | null = null
  let lastTransient: { status: number; statusText: string } | null = null
  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    try {
      res = await fetch(url, {
        method: 'POST',
        headers,
        body: JSON.stringify(baseBody)
      })
    } catch (err) {
      if (attempt === MAX_ATTEMPTS) {
        throw new Error(
          `Could not reach provider at ${base}. Check your network and base URL. (${(err as Error).message})`
        )
      }
      console.warn(`[provider] network error (attempt ${attempt}/${MAX_ATTEMPTS}): ${(err as Error).message} — retrying`)
      await sleep(backoffMs(attempt))
      continue
    }

    if (res.ok || !TRANSIENT_STATUSES.has(res.status)) break

    lastTransient = { status: res.status, statusText: res.statusText }
    if (attempt === MAX_ATTEMPTS) break
    console.warn(`[provider] ${res.status} ${res.statusText} (attempt ${attempt}/${MAX_ATTEMPTS}) — retrying`)
    await sleep(backoffMs(attempt))
  }

  if (!res) {
    // Unreachable — the loop either assigns res or throws — but satisfies the type checker.
    throw new Error('Provider call failed before any response.')
  }

  if (!res.ok && res.status === 400) {
    const errText = await res.text().catch(() => '')
    if (shouldFallbackToMaxTokens(errText)) {
      const fallbackBody: Record<string, unknown> = { model, messages, max_tokens: maxOut }
      if (opts.jsonMode) fallbackBody.response_format = { type: 'json_object' }
      res = await fetch(url, {
        method: 'POST',
        headers,
        body: JSON.stringify(fallbackBody)
      })
    } else {
      throw new Error(`OpenAI-compatible call failed: ${res.status} ${res.statusText}\n${errText}`)
    }
  }

  if (!res.ok) {
    if (lastTransient && TRANSIENT_STATUSES.has(res.status)) {
      throw new Error(
        `Provider temporarily unavailable (${res.status} ${res.statusText}). Tried ${MAX_ATTEMPTS} times. Please try again in a moment.`
      )
    }
    const body = await res.text().catch(() => '')
    throw new Error(`OpenAI-compatible call failed: ${res.status} ${res.statusText}\n${body}`)
  }

  const data = (await res.json()) as {
    choices?: { message?: { content?: string } }[]
  }
  const content = data.choices?.[0]?.message?.content
  if (!content) throw new Error('OpenAI-compatible response had no content.')
  return content
}

function backoffMs(attempt: number): number {
  const base = 1000 * Math.pow(2, attempt - 1)
  return base + Math.floor(Math.random() * 250)
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms))
}

function shouldFallbackToMaxTokens(errText: string): boolean {
  const t = errText.toLowerCase()
  return (
    (t.includes('max_completion_tokens') &&
      (t.includes('unknown') ||
        t.includes('unsupported') ||
        t.includes('not supported') ||
        t.includes('unrecognized') ||
        t.includes('not allowed'))) ||
    (t.includes('use') && t.includes('max_tokens'))
  )
}

// --- list / read ---

export function listDigests(db: DB): DigestInfo[] {
  const rows = db
    .prepare('SELECT date, path, generated_at as generatedAt FROM digests ORDER BY date DESC')
    .all() as DigestInfo[]
  return rows.filter((r) => fs.existsSync(r.path))
}

export async function readDigest(filePath: string): Promise<string> {
  return fsp.readFile(filePath, 'utf8')
}

/**
 * Returns a structured DigestDoc for a date — uses DB tables when present,
 * otherwise parses the on-disk markdown into sections with no references.
 */
export async function getDigestDoc(db: DB, date: string): Promise<DigestDoc> {
  const info = db
    .prepare('SELECT date, path, generated_at as generatedAt FROM digests WHERE date = ?')
    .get(date) as DigestInfo | undefined
  if (!info) throw new Error(`No digest for ${date}`)

  if (hasStructuredDigest(db, date)) {
    return readDigestDoc(db, info)
  }

  // Legacy fallback: parse the .md by ## headings.
  const md = await fsp.readFile(info.path, 'utf8').catch(() => '')
  const sections = parseLegacyMarkdown(md)
  return {
    info,
    sections: sections.map((s, i) => ({
      sectionId: s.sectionId || `section-${i + 1}`,
      heading: s.heading,
      kind: s.kind,
      bodyMd: s.bodyMd,
      items: s.items.map((it) => ({
        itemId: it.itemId,
        textMd: it.textMd,
        refs: [],
        refinedAt: null
      })),
      refs: [],
      refinedAt: null,
      hasHistory: false
    })),
    structured: false
  }
}

/**
 * Parse a markdown digest body into rough sections + bullets.
 * Best-effort — used only for digests generated before structured persistence existed.
 */
export function parseLegacyMarkdown(md: string): ParsedSection[] {
  if (!md) return []
  // Strip the leading H1 ("# Work Diary — …") and the trailing "## Sessions covered" footer.
  const lines = md.split(/\r?\n/)
  const sectionStarts: number[] = []
  for (let i = 0; i < lines.length; i++) {
    if (/^##\s+/.test(lines[i])) sectionStarts.push(i)
  }
  if (sectionStarts.length === 0) return []

  const out: ParsedSection[] = []
  for (let s = 0; s < sectionStarts.length; s++) {
    const start = sectionStarts[s]
    const end = s + 1 < sectionStarts.length ? sectionStarts[s + 1] : lines.length
    const headingLine = lines[start].replace(/^##\s+/, '').trim()
    if (/^sessions covered/i.test(headingLine)) continue // drop footer

    const bodyLines = lines.slice(start + 1, end).join('\n').trim()
    const sectionId = slugify(headingLine) || `section-${out.length + 1}`

    // Detect kind by counting list markers.
    const bulletLines = bodyLines.split(/\r?\n/).filter((l) => /^\s*[-*]\s+/.test(l))
    const nonBulletText = bodyLines
      .split(/\r?\n/)
      .filter((l) => l.trim() && !/^\s*[-*]\s+/.test(l))
      .join('\n')
      .trim()

    let kind: 'bullets' | 'paragraph' | 'mixed' = 'paragraph'
    if (bulletLines.length > 0 && !nonBulletText) kind = 'bullets'
    else if (bulletLines.length > 0) kind = 'mixed'

    const items: ParsedItem[] = bulletLines.map((l, i) => ({
      itemId: `i${i + 1}`,
      textMd: l.replace(/^\s*[-*]\s+/, '').trim(),
      refIds: []
    }))

    out.push({
      sectionId,
      ord: out.length,
      heading: headingLine,
      kind,
      bodyMd: bodyLines,
      items,
      refIds: []
    })
  }
  return out
}

/**
 * Used by digestRefine to update the on-disk .md after a section/item refine.
 */
export async function rewriteDigestFile(db: DB, date: string): Promise<void> {
  const info = db
    .prepare('SELECT date, path, generated_at as generatedAt FROM digests WHERE date = ?')
    .get(date) as DigestInfo | undefined
  if (!info) return
  const window = localDayWindow(date)
  const sessions = findSessionsInWindow(db, window.startIso, window.endIso)
  if (!hasStructuredDigest(db, date)) return // nothing to render
  const doc = readDigestDoc(db, info)
  const md = renderDocMarkdown(doc, sessions)
  await fsp.writeFile(info.path, md, 'utf8')
  const generatedAt = new Date().toISOString()
  db.prepare('UPDATE digests SET generated_at = ? WHERE date = ?').run(generatedAt, date)
}

/**
 * The day's full timeline, used by the refine UI's "add reference" picker.
 */
export async function listDigestTimeline(db: DB, date: string): Promise<DigestRef[]> {
  const window = localDayWindow(date)
  const sessions = findSessionsInWindow(db, window.startIso, window.endIso)
  return buildReferences(db, sessions)
}

// --- helpers ---

function extractText(blocks: ContentBlock[]): string {
  const parts: string[] = []
  for (const b of blocks) {
    if (b.type === 'text') parts.push(b.text)
    else if (b.type === 'thinking') parts.push(`(thinking) ${b.thinking}`)
    else if (b.type === 'tool_use') parts.push(`[tool: ${b.name}]`)
  }
  return parts.join('\n')
}

export const SYSTEM_PROMPT = `You are writing a personal work diary entry from coding-session transcripts. Be concise, concrete, and honest. Focus on decisions made, problems solved, questions that remained open, and patterns in how the user worked. Avoid filler.`

export function todayLocalISODate(): string {
  const now = new Date()
  const y = now.getFullYear()
  const m = String(now.getMonth() + 1).padStart(2, '0')
  const d = String(now.getDate()).padStart(2, '0')
  return `${y}-${m}-${d}`
}
